# Travis YAML based on idea at
# https://therenegadecoder.com/code/how-to-build-latex-with-travis-ci-and-minted/

language: generic
sudo: required
before_install:
# grab pandoc as well
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
before_script:
  # Change working directory so including files will work
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run_tests.sh
notifications:
  email: false
